### ISSUE TITLE
Por favor eliminar los Lorem

### ISSUE THREAD

**Issue by smltrs0** [MrRoiz/mobile-todo-list#1]
Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illo laborum
			atque facere enim, accusamus officiis voluptatem laboriosam pariatur,
			nulla laudantium magnam ad placeat excepturi. Animi possimus odit vitae
			dolores ratione!

**Comment by MrRoiz** [comment]
bro, todavia esta en desarrollo 🤣
